import os
import json

def create_project_structure():
    """Create the initial project structure"""
    directories = [
        "src",
        "src/database",
        "src/core",
        "src/utils",
        "src/data",
        "tests",
        "logs",
        "docs"
    ]
    
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
        with open(f"{directory}/__init__.py", "w") as f:
            f.write("# Generated by project initialization script")
            
    # Create base files
    files = {
        "README.md": "# MediterranIA Orchestrator\n\nOrchestrator per piani alimentari personalizzati",
        "requirements.txt": "numpy>=1.21.0\npandas>=1.3.0\npytest>=6.2.5\nlogging>=0.5.1.2\ntyping>=3.7.4.3",
        "setup.py": open("setup.py").read() if os.path.exists("setup.py") else ""
    }
    
    for filename, content in files.items():
        with open(filename, "w") as f:
            f.write(content)
            
    # Create .gitignore
    with open(".gitignore", "w") as f:
        f.write("""
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
logs/*
!logs/.gitkeep
        """)

if __name__ == "__main__":
    create_project_structure()
